// One-time: self-host the Google Fonts. Downloads the woff2 files (latin subset),
// writes them to public/fonts/, and prepends @font-face rules to the tokens module so the
// browser loads fonts from our own origin instead of fonts.gstatic.com.
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs'

const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
const cssUrl = 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Inter+Tight:wght@400;500;600;700&display=swap'
const KEEP = ['latin'] // en-GB (incl. £ and common accents) lives in the latin subset

const css = await (await fetch(cssUrl, { headers: { 'User-Agent': UA } })).text()
mkdirSync('public/fonts', { recursive: true })

const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([\s\S]*?)\}/g
let m, out = '', files = []
while ((m = re.exec(css))) {
  const subset = m[1], body = m[2]
  if (!KEEP.includes(subset)) continue
  const fam = (body.match(/font-family:\s*'([^']+)'/) || [])[1]
  const weight = (body.match(/font-weight:\s*(\d+)/) || [])[1]
  const url = (body.match(/src:\s*url\(([^)]+)\)\s*format\('woff2'\)/) || [])[1]
  const urange = (body.match(/unicode-range:\s*([^;]+);/) || [])[1] || ''
  if (!fam || !weight || !url) continue
  const slug = fam.toLowerCase().replace(/\s+/g, '-')
  const file = `${slug}-${weight}.woff2`
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer())
  writeFileSync(`public/fonts/${file}`, buf)
  files.push(file)
  out += `@font-face{font-family:'${fam}';font-style:normal;font-weight:${weight};font-display:swap;src:url(/fonts/${file}) format('woff2');${urange ? 'unicode-range:' + urange + ';' : ''}}\n`
}

const MARK = '/* self-hosted fonts (generated by scripts/fetch-fonts.mjs) */'
const gpath = 'src/styles/modules/tokens.css'
let g = readFileSync(gpath, 'utf8')
if (!g.includes(MARK)) {
  writeFileSync(gpath, MARK + '\n' + out + '\n' + g)
}
console.log('downloaded ' + files.length + ' font files:\n  ' + files.join('\n  '))
