import TreatmentPage from '../../components/TreatmentPage'

const data = {
  concern: {
    heading: (<><em>Missing teeth</em>, or dentures that have had their day?</>),
    body: ["Losing a tooth is never just cosmetic. The teeth either side start to drift, the bone beneath the gap slowly shrinks, and chewing on that side gets harder. Loose dentures bring their own daily frustrations, from sore spots to worrying they’ll slip at the worst moment.", "Implants put a stable, permanent tooth back where the gap is, or anchor a denture so it stops moving. From our Merchant City practice in Glasgow, we plan every case with a 3D CBCT scan, so you know exactly what is involved before you decide."],
    symptoms: ["A gap from a lost or extracted tooth", "A denture that clicks, slips or rubs", "Avoiding certain foods on one side", "Feeling self-conscious when you smile", "An old bridge that has seen better days"],
  },
  ctaPrimaryLabel: 'Book Free Consultation',
  lastReviewed: '2026-06-08',
  lastReviewedLabel: 'June 2026',
  slug: "dental-implants",
  side: "night",
  tag: "Permanent Solutions",
  h1Plain: "Dental Implants",
  procedureType: "SurgicalProcedure",
  title: (<>Dental implants, the closest thing <em>to a natural tooth</em></>),
  lead: "Losing a tooth affects more than how your smile looks. Dental implants at Day Night Dental replace the whole tooth, root and crown, so you can get back to eating, talking and smiling without thinking twice.",
  seo: { title: "Dental Implants in Glasgow | Day Night Dental", description: "Replace missing teeth with dental implants at Day Night Dental in Glasgow. Single implants, bridges and All-on-4, planned with on-site CBCT scanning." },
  meta: [{"k": "Suitable for", "v": "1 tooth to full arch", "tone": "night"}, {"k": "Implant lifespan", "v": "Designed to last", "tone": ""}, {"k": "Finance from", "v": "0% APR", "tone": "day"}],
  overviewHeading: (<>A <em>permanent</em> foundation for missing teeth</>),
  overview: ["A dental implant is a small titanium post that takes the place of a missing tooth root. Over a few months it fuses with your jawbone in a natural healing process called osseointegration. Once it has, it gives a really solid base for a crown, a bridge or a full set of replacement teeth that look and feel a lot like your own.", "Because the implant joins with the bone, it also helps protect the jaw, which tends to shrink once a tooth is gone. The result is built to last, with nothing slipping or clicking, and we never have to touch the healthy teeth on either side of the gap.", "Every implant treatment here starts with an on-site CBCT 3D scan, so your clinician can plan exactly where the implant goes around your nerves, sinuses and the bone you have. A single tooth, an implant-supported bridge or a full-arch restoration, it’s all planned around you, and we talk you through it properly before we start."],
  facts: [{"dt": "Best for", "dd": "Single, multiple or all missing teeth"}, {"dt": "Planning", "dd": "On-site CBCT 3D scan included"}, {"dt": "Options", "dd": "Single implants, bridges, All-on-4"}, {"dt": "Healing time", "dd": "Usually 3 to 6 months to integrate"}, {"dt": "Anaesthetic", "dd": "Local; sedation available in suitable cases"}],
  benefitsHeading: (<>Why patients choose <em>implants</em></>),
  benefits: [{"title": "Looks and feels natural", "body": "Your implant crown is colour-matched to the teeth around it, so most patients tell us they forget which tooth it is. It blends in and feels like your own."}, {"title": "Protects your other teeth", "body": "A bridge leans on the teeth either side of the gap. An implant stands on its own, so there’s no need to file down or rely on healthy teeth."}, {"title": "Helps preserve the jaw", "body": "Because it replaces the tooth root, an implant keeps the bone working and helps slow the bone loss that usually follows a missing tooth."}, {"title": "Built to last", "body": "Look after your implant with good brushing and regular check-ups and it’s designed to last many years. For most people that’s far longer than the alternatives."}],
  stepsHeading: (<>Your <em>implant</em> journey</>),
  steps: [{"title": "Consultation and CBCT scan", "body": "We check your mouth, take a 3D CBCT scan on-site and talk through what you want. You leave with a clear written plan, a timeline and the costs, all before any treatment starts."}, {"title": "Implant placement", "body": "With the area numbed under local anaesthetic, your clinician places the titanium implant into the jawbone. Most patients are surprised by how comfortable and quick the appointment turns out to be."}, {"title": "Healing and integration", "body": "Over the next few months the implant fuses with the bone. We can fit a temporary tooth so you’re never left with a visible gap while you heal."}, {"title": "Fitting your new tooth", "body": "Once the implant has integrated, we attach your custom-made crown, bridge or full-arch restoration. We check the fit, the bite and the finish before you go."}],
  faqHeading: (<>Dental implant questions, <em>answered</em></>),
  faqs: [{"q": "How much do dental implants cost?", "a": "A single dental implant, implant-supported bridges and full-arch options like All-on-4 are each priced case by case. The final figure comes down to how many implants you need and any preparatory work, and we put it all in writing after your consultation. Finance is available from 0% APR if you’d rather spread the cost."}, {"q": "Does getting a dental implant hurt?", "a": "Placement is done under local anaesthetic, so you shouldn’t feel pain at the time. Most patients tell us it was more comfortable than they’d feared. A bit of swelling or tenderness afterwards is normal and usually settles in a few days with ordinary pain relief. If you feel anxious, we can offer sedation in suitable cases."}, {"q": "How long does the whole process take?", "a": "From placement to your final tooth, treatment usually takes three to six months, because the implant needs time to fuse with the bone. Some cases can go quicker, and we often fit a temporary tooth so you’re not left with a gap. Your CBCT scan lets us give you a realistic timeline from the very first visit."}, {"q": "Are dental implants available on the NHS?", "a": "The NHS rarely funds dental implants. They’re usually only covered in specific situations, such as after facial trauma or certain medical conditions. For most people, implants are a private treatment. At Day Night Dental we offer them privately, with clear pricing and finance options."}, {"q": "Am I suitable for dental implants?", "a": "Plenty of adults with one or more missing teeth are suitable. It comes down to your gum health, your general health and how much jawbone you have. Your on-site CBCT scan lets us check this properly, and if bone is limited we can talk through options like grafting. The surest way to find out is a consultation."}],
  related: [{"slug": "cosmetic-dentistry", "title": "Cosmetic Dentistry", "tag": "Smile Design"}, {"slug": "general-dentistry", "title": "General Dentistry", "tag": "Foundation Care"}, {"slug": "emergency-dentist", "title": "Emergency Care", "tag": "24/7 Available"}],
  cta: { heading: (<>Book your<br /> <em>dental implant consultation</em></>), sub: "On-site CBCT planning and clear written quotes. Day and evening appointments, 7 days a week." },
}

export default function DentalImplants() {
  return <TreatmentPage data={data} />
}
