import TreatmentPage from '../../components/TreatmentPage'

const data = {
  concern: {
    heading: (<>Not sure when you <em>last had a look</em>?</>),
    body: ["It is easy to put off a check-up, especially when nothing hurts. The trouble is that early decay and gum problems rarely cause pain until they have already taken hold, so a mouth can feel fine while something is quietly getting worse.", "A routine examination is a gentle way to find out where things actually stand. We look at your teeth, gums and soft tissues, check for early signs of trouble, and tell you plainly what we find. If it has been years, or you feel nervous, that is completely normal and we go at your pace."],
    symptoms: ["A long gap since your last visit", "Bleeding gums when you brush", "Sensitivity or a niggle you keep ignoring", "Worry about something being missed", "Feeling nervous and putting it off"],
  },
  ctaPrimaryLabel: 'Book a Consultation',
  lastReviewed: '2026-06-16',
  lastReviewedLabel: 'June 2026',
  slug: "dental-check-ups",
  side: "night",
  tag: "Prevention",
  h1Plain: "Dental Check-ups",
  procedureType: "Dentistry",
  title: (<>The simplest way <em>to stay ahead</em> of dental problems</>),
  lead: "A check-up is the simplest way to keep your teeth healthy and avoid bigger problems later. We look closely at your teeth, gums and the soft tissues in your mouth, check for early signs of trouble, and give you a clear plan. Nothing rushed. Nothing hidden.",
  seo: { title: "Dental Check-ups in Glasgow | Day Night Dental", description: "Routine dental check-ups in Glasgow at Day Night Dental. Catch problems early and protect your teeth and gums. Day and evening appointments, 7 days a week." },
  meta: [{"k": "What it covers", "v": "Teeth, gums, soft tissues", "tone": "day"}, {"k": "X-rays", "v": "Only when needed", "tone": ""}, {"k": "Opening hours", "v": "Day and evening, 7 days", "tone": "night"}],
  overviewEyebrow: 'The Treatment',
  overviewHeading: (<>A thorough look at your <em>whole mouth</em></>),
  overview: ["A dental check-up is a thorough look at the whole of your mouth, not just your teeth. We check for decay, cracks and worn or failing fillings. We look at your gums for early signs of gum disease. We examine the soft tissues, your cheeks, tongue, lips, and the floor and roof of your mouth, including a mouth-cancer check, and we assess your jaw joint and bite. We take X-rays only when we actually need to see something a visual exam cannot show. Then we talk you through what we found and what, if anything, needs doing.", "The point of a regular check-up is to catch small problems while they are still small. A speck of decay is usually straightforward to treat, and sometimes it can be slowed or monitored rather than filled at all. Early gum disease (gingivitis) can often be reversed. Once it advances, the damage to the bone and tissue around your teeth cannot be undone, though it can usually be stabilised and kept under control. Problems found at a routine visit are often simpler and gentler to treat than problems left for years.", "Day Night Dental is based in Merchant City in central Glasgow, and we see patients from across the city. Because we open in the day and the evening, seven days a week, fitting a check-up around work or family is usually straightforward. If you are nervous, or it has been a long time since your last visit, that is completely normal and we will not make you feel awkward about it. Just tell us, and we will go at your pace."],
  facts: [{"dt": "What it covers", "dd": "Your teeth, gums and soft tissues, plus a mouth-cancer screening and a check of your jaw joint and bite, all in one appointment."}, {"dt": "X-rays", "dd": "Taken only when clinically needed, not automatically at every visit."}, {"dt": "Check-up vs scale and polish", "dd": "A check-up (the examination) and a scale and polish (the clean) are usually two separate things. You may need one, both or neither."}, {"dt": "How often to come back", "dd": "It depends on you. We set the interval based on your mouth and your risk, and we will explain why."}, {"dt": "Mouth-cancer check", "dd": "A quick, painless part of every routine exam. The exam is one of the regular chances for early signs to be picked up."}, {"dt": "Opening hours", "dd": "Day and evening, seven days a week, in Merchant City, central Glasgow."}],
  benefitsHeading: (<>Why a routine <em>check-up</em> is worth it</>),
  benefits: [{"title": "Problems caught early", "body": "When something is found at a routine visit, treatment is usually smaller, quicker and easier than if it had been left."}, {"title": "Healthier gums", "body": "Healthy gums are a major part of holding on to your natural teeth, since gum disease is a common reason people lose them."}, {"title": "Mouth-cancer screening as standard", "body": "Every routine exam includes checking the soft tissues for early signs, so it happens automatically."}, {"title": "A clear picture", "body": "You leave with an honest summary of your mouth and a plan you actually understand."}, {"title": "Advice tailored to you", "body": "You get guidance for your teeth, not generic tips, so home care actually works for you."}, {"title": "Less daunting", "body": "Small, regular visits are far less daunting than waiting until something hurts."}],
  stepsHeading: (<>What happens at your <em>appointment</em></>),
  steps: [{"title": "A quick catch-up", "body": "We ask about your general health, any medication you take, and anything that has been bothering you. Health changes can affect your mouth, so this matters more than it might seem."}, {"title": "The examination", "body": "We check each tooth for decay, cracks, wear and any fillings or restorations that are failing. We look at how your teeth meet and whether there are signs of grinding."}, {"title": "Gums and soft tissues", "body": "We assess your gum health and check the soft tissues of your mouth, throat and neck. This includes the mouth-cancer screening."}, {"title": "X-rays, only if needed", "body": "If something cannot be seen by eye, such as decay between teeth or bone level under the gum, we take a digital X-ray to check."}, {"title": "The plan", "body": "We tell you plainly what we found. If everything is fine, we say so. If something needs doing, we explain what, why, and how soon, and we answer your questions."}, {"title": "Next steps", "body": "We agree when you should come back and book any follow-up, such as a hygienist appointment or a filling, if you need one."}],
  aftercare: {
    eyebrow: "After your check-up",
    heading: "Keeping your mouth healthy between visits",
    intro: "What you do at home between check-ups matters just as much as the visit itself. Here is how to make the most of it.",
    phases: [
      { title: "Day to day", items: ["Follow the brushing and cleaning advice we give you. It will be specific to your mouth, not a generic script.", "Act on any diet or lifestyle points we raise. Cutting how often you have sugary food and drink can make a real difference.", "Keep an eye on your own mouth. If you notice a lump, an ulcer that has not healed in a few weeks, new pain, sensitivity or bleeding gums, get in touch. Do not wait for the next routine visit."] },
      { title: "Following up", items: ["Book any treatment or hygienist appointment we recommended while it is fresh.", "Tell us at each visit if your medication or general health has changed."] },
      { title: "Longer term", items: ["Come back when your check-up is due. The interval we set is there to keep you ahead of problems, not behind them."] },
    ],
  },
  risks: {
    eyebrow: "Honest notes",
    heading: (<>What a check-up <em>can and cannot do</em></>),
    body: ["A check-up tells us the state of your mouth on the day. It does not stop new problems appearing, which is exactly why regular visits and good home care both matter.", "We will not put you through X-rays for the sake of it, and we will not invent work you do not need. If we are unsure about something, we will say so and keep an eye on it rather than rush in.", "And if we do find something, finding it at a routine check-up is almost always far simpler to deal with, because that is when treatment is simplest."],
  },
  faqHeading: (<>Check-up questions, <em>answered</em></>),
  faqs: [{"q": "How often should I have a check-up?", "a": "It depends on you. For some people, longer gaps between visits are appropriate. Others, including children and anyone with a higher risk of decay or gum problems, are best seen more often. We will look at your mouth, set an interval that suits you, and tell you why. There is no single rule that fits everyone."}, {"q": "Does a check-up hurt?", "a": "No. A routine examination should not be painful. We are looking and gently checking, not treating. If anything feels tender we will stop and talk about it. For most people the whole thing is quick and easy."}, {"q": "Will I need X-rays?", "a": "Only if we need to see something a visual check cannot show, such as decay between teeth or bone level below the gum. They are not done automatically every time. When we do take one, we will explain why."}, {"q": "What is the difference between a check-up and a scale and polish?", "a": "A check-up is the examination, where we assess your teeth, gums and soft tissues. A scale and polish is a clean that removes the hardened plaque brushing cannot shift. They are usually separate appointments. You might need just the check-up, both, or neither on a given visit."}, {"q": "What happens if you find a problem?", "a": "We tell you straight away, in plain terms. We explain what it is, what your options are, and how urgent it is. Nothing happens without you understanding it and agreeing to it first. Catching a problem early usually means a smaller, simpler fix."}, {"q": "I'm nervous about the dentist. Can you help?", "a": "Yes, and you are far from alone. Tell us you are anxious and we will slow down, explain each step before we do it, and let you take breaks. A check-up is a gentle place to start rebuilding your confidence, because it is just looking, not treating."}, {"q": "It's been years since I last went. Is that a problem?", "a": "Not for us. Plenty of our patients come back after a long gap, often because they were nervous or life got in the way. We will not lecture you. We will simply have a careful look, tell you where things stand, and sort out a sensible plan from there."}],
  related: [{"slug": "dental-hygiene", "title": "Dental Hygiene", "tag": "Prevention"}, {"slug": "gum-disease-treatment", "title": "Gum Disease Treatment", "tag": "Gum Health"}, {"slug": "nervous-patients", "title": "Nervous Patients", "tag": "Gentle Care"}],
  cta: { heading: (<>Book your<br /> <em>dental check-up</em></>), sub: "A careful look and an honest plan, with no pressure. Day and evening appointments, seven days a week." },
}

export default function DentalCheckUps() {
  return <TreatmentPage data={data} />
}
