import TreatmentPage from '../../components/TreatmentPage'

const data = {
  ctaPrimaryLabel: 'Book Emergency Appointment',
  lastReviewed: '2026-06-08',
  lastReviewedLabel: 'June 2026',
  slug: "emergency-dentist",
  side: "night",
  tag: "24/7 Available",
  h1Plain: "Emergency Dentist",
  procedureType: "Dentistry",
  title: (<>Emergency dentist in Glasgow. <em>We are awake and ready</em></>),
  lead: "Our emergency line is open every hour of every day. So when you get sudden toothache, a broken crown or a knocked-out tooth, you can call for urgent help straight away. Most patients are seen the same day.",
  seo: { title: "Emergency Dentist in Glasgow | Day Night Dental", description: "Need an emergency dentist in Glasgow? Day Night Dental has a 24-hour helpline, same-day appointments and out-of-hours care. Pain relief first, 7 days a week." },
  meta: [{"k": "Helpline", "v": "Open 24/7", "tone": "night"}, {"k": "Seen", "v": "Same day, typically", "tone": "day"}, {"k": "First priority", "v": "Pain relief", "tone": ""}],
  overviewHeading: (<>Help <em>when you need it</em>, not just office hours</>),
  overview: ["A throbbing toothache at 2am, a crown that comes loose over the weekend, a tooth knocked out on the sports pitch. These are exactly the moments Day Night Dental was built for. Our practice is in Merchant City, in the heart of central Glasgow, and our 24-hour emergency helpline is open day or night. Wherever you are in the city, the West End, Dennistoun or the Southside, you can call straight away rather than waiting until Monday.", "We keep same-day appointments in reserve every day, because emergencies simply cannot be booked in advance. When you call, we settle your pain first, then work out what is causing it and talk you through your options before any treatment goes ahead. You will know where you stand.", "We see everything from abscesses and severe toothache to broken, chipped or knocked-out teeth and lost fillings or crowns. Our out-of-hours surgery is set up to assess the problem and get it under control. If a tooth can be saved, we will always try. If it cannot, we will be straight with you and focus on getting you comfortable."],
  facts: [{"dt": "Best for", "dd": "Toothache, abscesses, broken or knocked-out teeth, lost crowns and fillings"}, {"dt": "Helpline", "dd": "24 hours a day, 7 days a week"}, {"dt": "Seen by", "dd": "Same-day appointments held in reserve daily"}, {"dt": "Out of hours", "dd": "Evening, overnight and weekend cover available"}, {"dt": "First step", "dd": "Pain relief, then diagnosis and clear options"}],
  benefitsHeading: (<>Why patients call us in a <em>crisis</em></>),
  benefits: [{"title": "An emergency line, always open", "body": "Our 24-hour emergency line is there at any hour. The moment something goes wrong, day or night, weekday or weekend, you get fast, clear guidance on what to do next."}, {"title": "Same-day appointments reserved", "body": "We deliberately keep slots free every single day for emergencies. Most patients who call are seen the same day, rather than being told to wait until the next routine opening."}, {"title": "Pain relief comes first", "body": "Before anything else, we focus on getting you out of pain. Once you are comfortable, we move on to working out the cause and talking through what happens next."}, {"title": "Honest, clear options", "body": "We explain what is wrong in plain language, set out your choices and the likely costs, and never push treatment on you. You decide, with all the facts in front of you."}],
  stepsHeading: (<>What happens <em>when you call</em></>),
  steps: [{"title": "Call the 24/7 helpline", "body": "Ring our emergency line at any hour. A clinician will talk through your symptoms, give immediate self-care advice and decide how urgently you need to be seen."}, {"title": "Get a same-day slot", "body": "In most cases we will offer you an appointment that same day, using the emergency slots we hold in reserve. For overnight calls we arrange the soonest suitable out-of-hours time."}, {"title": "Pain relief and diagnosis", "body": "At the surgery we settle your pain first, then examine the area and, where needed, take an X-ray to pinpoint exactly what is causing the problem."}, {"title": "Treatment and aftercare", "body": "We carry out the treatment that stabilises the tooth, explain how to care for it afterwards and arrange any follow-up. You leave knowing what to expect next."}],
  faqHeading: (<>Emergency dentist questions, <em>answered</em></>),
  faqs: [{"q": "How much does an emergency dental appointment cost?", "a": "An emergency assessment at Day Night Dental covers the consultation, pain relief and diagnosis. Any further treatment, such as a filling, extraction or root canal, is quoted separately and explained to you before we begin. We will always confirm the cost upfront so there are no surprises."}, {"q": "Can I really be seen the same day?", "a": "In most cases, yes. We hold same-day appointments in reserve every day specifically for emergencies, so patients who call our helpline are usually seen within hours. For overnight or out-of-hours calls, we arrange the earliest suitable appointment and give you advice to manage symptoms until then."}, {"q": "What counts as a dental emergency?", "a": "Severe or worsening toothache, facial swelling or an abscess, a knocked-out or badly broken tooth, uncontrolled bleeding, and lost crowns or fillings causing pain are all good reasons to call. A knocked-out adult tooth in particular is time-critical, so ring us straight away rather than waiting. If you are unsure, call and we will help you judge how urgent it is."}, {"q": "Is emergency dental care available on the NHS?", "a": "The NHS does provide urgent dental care, but availability is often limited and can involve long waits or no local slots, especially out of hours. Day Night Dental is a private practice, which means we can offer a 24-hour helpline and same-day appointments without that uncertainty. We are happy to explain our charges before you commit."}, {"q": "What should I do while I wait to be seen?", "a": "For pain, an over-the-counter painkiller you normally tolerate can help, and a cold compress against the cheek may ease swelling. For a knocked-out adult tooth, hold it by the crown, avoid touching the root, and keep it in milk or saliva until you reach us. Our helpline clinician will give you specific advice for your situation when you call."}],
  related: [{"slug": "general-dentistry", "title": "General Dentistry", "tag": "Foundation Care"}, {"slug": "dental-implants", "title": "Dental Implants", "tag": "Permanent Solutions"}, {"slug": "cosmetic-dentistry", "title": "Cosmetic Dentistry", "tag": "Smile Design"}],
  cta: { heading: (<>In pain? Call our<br /> <em>24/7 emergency line</em></>), sub: "A clinician is ready to help right now. Most patients are seen the same day." },
}

export default function EmergencyDentist() {
  return <TreatmentPage data={data} />
}
