import TreatmentPage from '../../components/TreatmentPage'

const data = {
  slug: "inlays-onlays",
  side: "day",
  tag: "Tooth Repair",
  h1Plain: "Inlays and Onlays",
  procedureType: "MedicalProcedure",
  ctaPrimaryLabel: 'Book a Consultation',
  lastReviewed: '2026-06-16',
  lastReviewedLabel: 'June 2026',
  title: (<>A precise, lab-made repair, the <em>sensible middle ground</em></>),
  lead: "A precise, lab-made repair for a tooth that is too damaged for a normal filling but does not yet need a full crown.",
  seo: { title: "Inlays and Onlays in Glasgow | Day Night Dental", description: "Tooth-coloured inlays and onlays in Glasgow. A precise, lab-made middle ground between a filling and a crown. Day and evening appointments, 7 days a week." },
  meta: [{"k": "Best for", "v": "Heavily filled back teeth", "tone": "day"}, {"k": "Visits", "v": "Usually two", "tone": ""}, {"k": "Finish", "v": "Tooth-coloured", "tone": "night"}],
  overviewEyebrow: 'The Treatment',
  overviewHeading: (<>Stronger than a filling, kinder than a <em>crown</em></>),
  overview: ["Sometimes a tooth has lost too much structure for a standard filling to hold up, but there is still plenty of healthy tooth left. An inlay or onlay sits in that gap. It is a single solid piece, made to fit your tooth exactly, then bonded into place. It is typically stronger than a large filling and usually preserves more of your natural tooth than a crown. Think of it as the sensible middle ground.", "At Day Night Dental in Merchant City, central Glasgow, we use inlays and onlays mainly on back teeth, the molars and premolars that do the heavy chewing. They are tooth-coloured, so once they are fitted you would struggle to tell them apart from the rest of your tooth. We see patients from across Glasgow for this, often where an old, large filling has cracked or broken and a quick patch just will not last.", "If you are not sure whether your tooth needs an inlay, an onlay, a filling or a crown, that is fine. That is what the assessment is for. We will look at how much tooth is left, where the damage is, and how the tooth bites together, then talk you through the honest options. We are open day and evening, seven days a week, so you can come in at a time that suits you rather than taking a day off work."],
  facts: [{"dt": "What an inlay is", "dd": "An inlay fits inside the biting surface of the tooth, within the raised points called cusps. It is like a larger, more precise filling."}, {"dt": "What an onlay is", "dd": "An onlay does the same job but also covers one or more of those cusps, or the whole biting surface. It is sometimes called a partial crown."}, {"dt": "How they are made", "dd": "Both are made outside the mouth in a dental laboratory, then bonded onto the prepared tooth."}, {"dt": "Materials", "dd": "They are usually made from tooth-coloured porcelain, ceramic or composite. Composite is typically less hard-wearing than porcelain or ceramic, so the dentist will advise which suits the tooth. Gold is also possible but is not tooth-coloured."}, {"dt": "Where they are used", "dd": "They are most often used on back teeth that take the most chewing force."}, {"dt": "Tooth preserved", "dd": "An inlay or onlay usually removes less healthy tooth than a crown does, so more of your own tooth is kept."}],
  concern: {
    heading: (<>An old filling that keeps <em>breaking down</em>?</>),
    body: ["A large filling that cracks or chips, or a back tooth that twinges when you chew, is often a sign the repair has been asked to do more than it can hold. A quick patch on top tends not to last, and each round of drilling takes away a little more tooth.", "An inlay or onlay can step in here, reinforcing a heavily filled or cracked back tooth while keeping more of your natural tooth than a crown would. If any of the below sounds familiar, it is worth getting the tooth looked at before the damage spreads."],
    symptoms: ["A large old filling that has cracked or broken", "A back tooth that aches when you bite down", "A filling that keeps coming loose or wearing away", "Sensitivity in a heavily filled molar", "A tooth you suspect is too far gone for another filling"],
  },
  benefitsHeading: (<>Why choose an inlay or <em>onlay</em></>),
  benefits: [{"title": "More hard-wearing than a large filling", "body": "Often more hard-wearing than a large filling, because the material is made and shaped before it is bonded in rather than packed in soft."}, {"title": "Keeps more of your natural tooth", "body": "Usually preserves more natural tooth than a crown, which is better for the tooth in the long run."}, {"title": "Tooth-coloured and discreet", "body": "Tooth-coloured options blend in, so the repair is hard to spot."}, {"title": "A precise, comfortable fit", "body": "A precise fit means a comfortable bite and a smooth edge that is easier to keep clean."}, {"title": "Replaces and reinforces", "body": "Can replace an old, broken or worn filling and help protect a weakened tooth from cracking further."}, {"title": "Good for a heavily filled back tooth", "body": "A sensible option for a cracked or heavily filled back tooth that needs reinforcing."}],
  stepsHeading: (<>Your <em>treatment</em> journey</>),
  steps: [{"title": "Assessment", "body": "We check the tooth, take any X-rays we need, and decide whether an inlay, onlay, filling or crown is the right call. We explain why."}, {"title": "Prepare the tooth", "body": "We numb the area with local anaesthetic, remove any decay or the old filling, and shape the tooth so the new piece will fit and bond well."}, {"title": "Scan or impression", "body": "We take a digital scan or a mould of the tooth so the inlay or onlay can be made to match it exactly, including how it meets the tooth above or below."}, {"title": "Temporary cover", "body": "We fit a temporary filling to protect the tooth while the permanent piece is being made in the laboratory."}, {"title": "Fit and bond", "body": "At the second visit we remove the temporary, check the new piece fits, then bond it firmly in place."}, {"title": "Bite check", "body": "We check how the tooth bites and make small adjustments so it feels right. You leave with a fully working tooth."}],
  aftercare: {
    eyebrow: "Looking after it",
    heading: "Aftercare",
    intro: "Most inlays and onlays take two short visits, usually a couple of weeks apart. Here is how to look after the tooth at each stage.",
    phases: [{"title": "The first few days", "items": ["Mild sensitivity, especially to hot and cold, is normal for a few days and usually settles by itself.", "The bite may feel slightly different at first. Give it a little time to settle in.", "If the tooth still feels high when you bite down after a few days, or the discomfort is not easing, give us a ring. A quick adjustment usually sorts it."]}, {"title": "While the temporary is in (between visits)", "items": ["Go easy on hard, sticky or chewy foods on that side, as they can lift a temporary filling.", "Try to chew on the other side where you can.", "Keep brushing gently around the area to keep it clean."]}, {"title": "Long term", "items": ["Brush twice a day with a fluoride toothpaste, including around the restored tooth.", "Clean between your teeth daily with floss or interdental brushes, especially at the edges of the restoration where decay can start.", "Keep up with routine check-ups and hygiene visits so we can keep an eye on the tooth and the repair.", "If you grind or clench your teeth, mention it. A nightguard can protect the work."]}],
  },
  risks: {
    eyebrow: "The trade-offs",
    heading: "Honest considerations",
    body: ["We would rather you know the trade-offs up front.", "An inlay or onlay is more involved than a simple filling. It usually means two visits and a wait while the piece is made in the laboratory.", "Some short-term sensitivity after fitting is common and normally passes.", "There is a small chance that a tooth which has had a lot of work needs further treatment later, such as root canal treatment, if the nerve becomes irritated. This is uncommon but worth knowing.", "Decay can still form at the edges of any restoration if cleaning slips, so day-to-day care matters.", "How long it lasts depends on the tooth, your bite, whether you grind, and your oral hygiene, and no one can promise an exact lifespan.", "Gold is hard-wearing but is not tooth-coloured, so material choice is a balance between how it looks and how it stands up to wear.", "Catching damage early often means more options and a better chance of preserving tooth with an inlay or onlay rather than moving straight to a crown, so it is worth getting a niggling back tooth checked."],
  },
  faqHeading: (<>Inlay and onlay questions, <em>answered</em></>),
  faqs: [{"q": "What is the difference between an inlay and an onlay?", "a": "Both are made-to-fit repairs that are bonded onto a tooth. An inlay sits within the cusps, inside the biting surface, a bit like a larger filling. An onlay also covers one or more of the cusps or the whole biting surface, which is why it is sometimes called a partial crown. The right one depends on how much of the tooth is damaged."}, {"q": "When would I need one instead of a filling or a crown?", "a": "When a tooth has more damage or decay than a normal filling can reliably hold, but enough healthy tooth is left that a full crown would remove more than necessary. They are also used to replace large fillings that keep breaking, or to strengthen a cracked back tooth. We decide based on how much sound tooth remains and where the damage is."}, {"q": "Does getting an inlay or onlay hurt?", "a": "The tooth is numbed with local anaesthetic first, so you should not feel pain during the preparation. Afterwards some mild sensitivity for a few days is normal and usually settles on its own. If you are nervous, tell us. We will go at your pace and explain each step."}, {"q": "How many visits does it take, and how long overall?", "a": "Usually two visits a couple of weeks apart. The first prepares the tooth and takes the scan or impression. The piece is then made in the laboratory, and the second visit fits and bonds it."}, {"q": "Will it be noticeable?", "a": "Porcelain, ceramic and composite inlays and onlays are tooth-coloured and matched to your tooth, so they are hard to spot once fitted. Gold is an option if you want a hard-wearing material on a back tooth, but it is not tooth-coloured."}, {"q": "How long do inlays and onlays last?", "a": "It depends on the tooth, your bite, whether you grind your teeth, and how well you clean. We cannot give a guaranteed lifespan, but looking after it well gives it the best chance."}, {"q": "Is there any special aftercare?", "a": "Nothing complicated. Brush twice a day with fluoride toothpaste, clean between your teeth daily, and keep up your check-ups. While a temporary is in place, go easy on hard and sticky foods on that side. If you grind your teeth, a nightguard helps protect the work."}],
  related: [{"slug": "white-fillings", "title": "White Fillings", "tag": "Tooth Repair"}, {"slug": "dental-crowns", "title": "Dental Crowns", "tag": "Tooth Repair"}, {"slug": "root-canal-treatment", "title": "Root Canal Treatment", "tag": "Saving Teeth"}],
  cta: { heading: (<>Book your<br /> <em>inlay or onlay consultation</em></>), sub: "We will look at the tooth and talk you through the honest options. Day and evening appointments, seven days a week." },
}

export default function InlaysOnlays() {
  return <TreatmentPage data={data} />
}
