import TreatmentPage from '../../components/TreatmentPage'

const data = {
  concern: {
    heading: (<>Teeth looking <em>yellow, dull or stained</em>?</>),
    body: ["Tea, coffee, red wine and time all leave their mark, and over-the-counter kits rarely make much difference. It’s one of the first things people notice, and one of the easiest to put right safely.", "Professional whitening at our Glasgow practice is dentist-led and far stronger than anything you can buy on the high street, with your comfort and any sensitivity carefully managed throughout."],
    symptoms: ["Yellowing or dull-looking teeth", "Stains from tea, coffee or red wine", "High-street kits that did nothing", "Wanting a brighter smile for an event", "Worry about sensitivity from whitening"],
  },
  ctaPrimaryLabel: 'Book Free Consultation',
  lastReviewed: '2026-06-08',
  lastReviewedLabel: 'June 2026',
  slug: "teeth-whitening",
  side: "day",
  tag: "Brighter Smile",
  h1Plain: "Teeth Whitening",
  procedureType: "CosmeticProcedure",
  title: (<>Teeth whitening, done properly. <em>Brighter and even</em></>),
  lead: "A dentist-led whitening plan that lifts years of staining and brings back a naturally brighter smile. We keep a close eye on sensitivity the whole way through.",
  seo: { title: "Teeth Whitening in Glasgow | Enlighten, Day Night", description: "Professional Enlighten teeth whitening at Day Night Dental in Glasgow. Dentist-led, sensitivity managed, day and evening appointments, 7 days a week." },
  meta: [{"k": "Treatment time", "v": "2 to 3 weeks", "tone": "day"}, {"k": "Results", "v": "Noticeably brighter", "tone": ""}, {"k": "Top-up trays", "v": "Take-home included", "tone": "night"}],
  overviewHeading: (<>Whitening that's <em>measured, not guessed</em></>),
  overview: ["Coffee, tea, red wine, certain foods and simply getting older all leave their mark on enamel over time. Shop-bought strips and high-street kits work at a fixed, low concentration, so they can't be tailored to your teeth. That's usually why the results look patchy and don't last. Professional whitening at Day Night Dental starts with an examination, so we know your teeth and gums are healthy enough to whiten and we can plan the right system for you.", "We use the Enlighten Evolution system, often paired with custom take-home trays and an optional in-chair acceleration appointment. We take impressions to make trays that fit precisely, which keeps the whitening gel on your teeth and off your gums. You wear the trays at home for a couple of weeks, and where it suits we finish with a session in the practice.", "Because a dentist leads the whole thing, we can adjust the gel strength, wear time and pacing to suit you, and step in quickly if any sensitivity shows up. Whitening lightens natural tooth structure. It won't change the colour of fillings, crowns or veneers, so if you have visible restorations we'll talk you through what to expect before you start."],
  facts: [{"dt": "Best for", "dd": "Yellowing, age-related and dietary staining on natural teeth"}, {"dt": "Systems used", "dd": "Enlighten Evolution and combination home-plus-chair protocols"}, {"dt": "Sensitivity", "dd": "Managed throughout; most patients find it temporary and mild"}, {"dt": "Not suitable for", "dd": "Matching crowns, veneers or fillings to a new shade"}, {"dt": "Longevity", "dd": "Typically lasts well with occasional top-ups using your trays"}],
  benefitsHeading: (<>Why choose <em>dentist-led</em> whitening</>),
  benefits: [{"title": "Clinically proven systems", "body": "We use established professional systems like Enlighten Evolution, applied at concentrations only a regulated practice can provide. That gives you more even, reliable results than any kit."}, {"title": "Custom-fitted trays", "body": "Trays are made from impressions of your own teeth, so the gel sits exactly where it should. That means better whitening and far less contact with your gums."}, {"title": "Sensitivity managed", "body": "Whitening can bring on some temporary sensitivity. We plan for it, adjust your treatment and suggest desensitising products, so most patients stay comfortable throughout."}, {"title": "Top-up trays to keep", "body": "Your custom trays are yours to keep. A short refresher every so often keeps your smile bright over the long term, without starting from scratch."}],
  stepsHeading: (<>Your <em>whitening</em> journey</>),
  steps: [{"title": "Consultation and check-up", "body": "We examine your teeth and gums, discuss your goals and record your current shade. This confirms whitening is suitable and lets us recommend the right system for you."}, {"title": "Custom trays made", "body": "We take impressions or scans and craft bespoke whitening trays. At your fitting we check they sit comfortably and show you exactly how to apply the gel."}, {"title": "Whitening at home", "body": "You wear your trays as directed over roughly two weeks, usually overnight or for set daytime periods. We stay in touch to monitor progress and manage any sensitivity."}, {"title": "In-chair finish and review", "body": "Where suitable, we finish with an in-practice acceleration session, then review your results together and give you guidance on maintaining your brighter smile."}],
  faqHeading: (<>Teeth whitening: <em>common questions</em></>),
  faqs: [{"q": "How much does teeth whitening cost?", "a": "The cost of professional whitening at Day Night Dental depends on the system and whether you add an in-chair session. We'll confirm the exact price after your consultation, and there's no obligation to go ahead. Ask our team about payment options when you book."}, {"q": "Does teeth whitening hurt?", "a": "Whitening itself isn't painful, though some people notice short-lived sensitivity to cold during or just after treatment. Because a dentist leads it, we adjust the gel strength and timing and suggest desensitising products. Most patients find any sensitivity mild and temporary."}, {"q": "How long does whitening take and how long do results last?", "a": "Most home plans run over roughly two to three weeks, with an optional in-chair appointment to finish. Results vary from person to person, but with care and the occasional top-up using your trays, a brighter shade tends to last well. Going easy on coffee, tea, red wine and smoking helps it last longer."}, {"q": "Is teeth whitening available on the NHS?", "a": "Whitening is a cosmetic treatment and isn't normally available on the NHS, so it's provided privately. As a private, GDC-regulated practice, we only carry out whitening after a dental examination, which is safer and also legally required. Be wary of unregulated high-street or online kits that skip this step."}, {"q": "Will whitening work on crowns, veneers or fillings?", "a": "Whitening lightens natural tooth enamel but won't change the colour of crowns, veneers or fillings. If you have visible restorations, we'll talk it through at your consultation, as you may want them reviewed or replaced afterwards so everything matches your new shade."}],
  related: [{"slug": "cosmetic-dentistry", "title": "Cosmetic Dentistry", "tag": "Smile Design"}, {"slug": "invisalign", "title": "Invisalign®", "tag": "Clear Aligners"}, {"slug": "general-dentistry", "title": "General Dentistry", "tag": "Foundation Care"}],
  cta: { heading: (<>Book your professional<br /> <em>teeth whitening consultation</em></>), sub: "Day and evening appointments in Glasgow, 7 days a week." },
}

export default function TeethWhitening() {
  return <TreatmentPage data={data} />
}
